In [68]:
# Install Groq SDK

!pip install -q groq

print("Groq package installed successfully.")

Groq package installed successfully.

In [69]:
# Import libraries required for data analysis and AI interaction

import pandas as pd
import json
from groq import Groq

print("Required libraries imported successfully.")

Required libraries imported successfully.

In [70]:
# Load CSV dataset into a pandas DataFrame

df = pd.read_csv("/content/student_performance.csv")

print("Dataset loaded successfully.")

# Display first 5 records
display(df.head())

Dataset loaded successfully.

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [71]:
# Display dataset information

print("Dataset Shape:")
print(df.shape)

print("\nDataset Columns:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("\nDataset information displayed successfully.")

Dataset Shape:
(30, 13)

Dataset Columns:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             30 non-null     int64
 1   name                   30 non-null     object
 2   age                    30 non-null     int64
 3   gender                 30 non-null     object
 4   department             30 non-null     object
 5   semester               30 non-null     int64
 6   math_score             30 non-null     int64
 7   science_score          30 non-null     int64
 8   english_score          30 non-null     int64
 9   programming_score      30 non-null     int64
 10  attendance_percentage  30 non-null     int64
 11  city                   30 non-null     object
 12  admission_year         30 non-null     int64
dtypes: int64(9), object(4)
memory usage: 3.2+ KB

Dataset information displayed successfully.

In [72]:
# Generate statistical summary of numerical columns

display(df.describe())

print("Statistical summary generated successfully.")

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

Statistical summary generated successfully.

In [73]:
# Replace with your Groq API Key

GROQ_API_KEY = "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"

# Create Groq client

client = Groq(
    api_key=GROQ_API_KEY
)

print("Groq client initialized successfully.")

Groq client initialized successfully.

In [74]:
# Function to analyze dataset using Groq-generated Pandas code

def analyze_data_with_groq(question, dataframe):

    """
    Purpose:
    --------
    Accepts a natural language question,
    generates Pandas code using Groq,
    executes the code,
    and returns JSON output.
    """

    print("Starting AI data analysis.")

    # Sample dataset records sent to Groq
    df_sample = dataframe.head().to_string()

    # Prompt sent to Groq
    prompt = f"""
You are an expert Python Data Analyst.

DataFrame name: df

Columns:
{dataframe.columns.tolist()}

Sample Data:
{df_sample}

Rules:
1. Generate only executable Python code.
2. Store final answer in variable named result.
3. Output must be JSON compatible.
4. No markdown.
5. No explanation.

Question:
{question}
"""

    try:

        print("Sending request to Groq.")

        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0
        )

        print("Response received from Groq.")

        generated_code = response.choices[0].message.content

        print("\nGenerated Code:")
        print("--------------------------------")
        print(generated_code)
        print("--------------------------------")

        # Remove markdown formatting if generated
        generated_code = generated_code.replace(
            "```python",
            ""
        )

        generated_code = generated_code.replace(
            "```",
            ""
        )

        print("Executing generated code.")

        # Local scope for execution
        local_scope = {
            "df": dataframe
        }

        # Execute code
        exec(
            generated_code,
            {},
            local_scope
        )

        print("Code executed successfully.")

        # Get result variable
        result = local_scope.get(
            "result",
            "No result generated."
        )

        # JSON output
        json_output = {
            "status": "success",
            "question": question,
            "result": result
        }

        print("\nJSON Output:")

        print(
            json.dumps(
                json_output,
                indent=4,
                default=str
            )
        )

        print("\nAnalysis completed successfully.")

        return json_output

    except Exception as e:

        error_output = {
            "status": "error",
            "question": question,
            "error_message": str(e)
        }

        print(
            json.dumps(
                error_output,
                indent=4
            )
        )

        return error_output

In [75]:
# Calculate average math score

result = analyze_data_with_groq(
    "What is the average math score?",
    df
)

print("Query executed successfully.")

Starting AI data analysis.
Sending request to Groq.
Response received from Groq.

Generated Code:
--------------------------------
result = df['math_score'].mean().to_json()
--------------------------------
Executing generated code.
{
    "status": "error",
    "question": "What is the average math score?",
    "error_message": "'numpy.float64' object has no attribute 'to_json'"
}
Query executed successfully.

In [76]:
# Department with highest average programming score

result = analyze_data_with_groq(
    "Which department has highest average programming score?",
    df
)

print("Query executed successfully.")

Starting AI data analysis.
Sending request to Groq.
Response received from Groq.

Generated Code:
--------------------------------
```python
import pandas as pd

# Assuming df is already created
result = df.groupby('department')['programming_score'].mean().to_dict()

print(result)
```

This code will output a dictionary where the keys are the department names and the values are the average programming scores for each department.
--------------------------------
Executing generated code.
{
    "status": "error",
    "question": "Which department has highest average programming score?",
    "error_message": "invalid syntax (<string>, line 10)"
}
Query executed successfully.

In [77]:
# Count male and female students

result = analyze_data_with_groq(
    "How many male and female students are there?",
    df
)

print("Query executed successfully.")

Starting AI data analysis.
Sending request to Groq.
Response received from Groq.

Generated Code:
--------------------------------
```python
import pandas as pd

# Assuming df is already created
df = pd.DataFrame({
   'student_id': [1001, 1002, 1003, 1004, 1005],
   'name': ['Aarav Sharma', 'Priya Patel', 'Rohit Verma', 'Sneha Reddy', 'Arjun Nair'],
   'age': [19, 20, 19, 20, 19],
   'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
   'department': ['Computer Science', 'Computer Science', 'Electronics', 'Mechanical', 'Computer Science'],
   'semester': [2, 2, 2, 2, 2],
   'math_score': [85, 76, 65, 70, 92],
   'science_score': [78, 82, 74, 80, 88],
   'english_score': [72, 88, 61, 75, 81],
   'programming_score': [91, 79, 55, 48, 95],
   'attendance_percentage': [92, 87, 78, 95, 90],
   'city': ['Mumbai', 'Ahmedabad', 'Delhi', 'Hyderabad', 'Kochi'],
   'admission_year': [2023, 2023, 2023, 2023, 2023]
})

# Count male and female students
male_students = df[df['gender'] == 'Male'].shape[0]
female_students = df[df['gender'] == 'Female'].shape[0]

# Store result in a dictionary
result = {
    'male_students': male_students,
    'female_students': female_students
}

print(result)
```
--------------------------------
Executing generated code.
{'male_students': 3, 'female_students': 2}
Code executed successfully.

JSON Output:
{
    "status": "success",
    "question": "How many male and female students are there?",
    "result": {
        "male_students": 3,
        "female_students": 2
    }
}

Analysis completed successfully.
Query executed successfully.

In [78]:
# Student with highest programming score

result = analyze_data_with_groq(
    "Who scored highest in programming?",
    df
)

print("Query executed successfully.")

Starting AI data analysis.
Sending request to Groq.
Response received from Groq.

Generated Code:
--------------------------------
```python
import pandas as pd

# Assuming df is already created
df = pd.DataFrame({
    'student_id': [1001, 1002, 1003, 1004, 1005],
    'name': ['Aarav Sharma', 'Priya Patel', 'Rohit Verma', 'Sneha Reddy', 'Arjun Nair'],
    'age': [19, 20, 19, 20, 19],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'department': ['Computer Science', 'Computer Science', 'Electronics', 'Mechanical', 'Computer Science'],
    'semester': [2, 2, 2, 2, 2],
    'math_score': [85, 76, 65, 70, 92],
    'science_score': [78, 82, 74, 80, 88],
    'english_score': [72, 88, 61, 75, 81],
    'programming_score': [91, 79, 55, 48, 95],
    'attendance_percentage': [92, 87, 78, 95, 90],
    'city': ['Mumbai', 'Ahmedabad', 'Delhi', 'Hyderabad', 'Kochi'],
    'admission_year': [2023, 2023, 2023, 2023, 2023]
})

# Find the student who scored highest in programming
result = df.loc[df['programming_score'].idxmax()]

print(result.to_json(orient='records'))
```
--------------------------------
Executing generated code.
[1005,"Arjun Nair",19,"Male","Computer Science",2,92,88,81,95,90,"Kochi",2023]
Code executed successfully.

JSON Output:
{
    "status": "success",
    "question": "Who scored highest in programming?",
    "result": "student_id                           1005\nname                           Arjun Nair\nage                                    19\ngender                               Male\ndepartment               Computer Science\nsemester                                2\nmath_score                             92\nscience_score                          88\nenglish_score                          81\nprogramming_score                      95\nattendance_percentage                  90\ncity                                Kochi\nadmission_year                       2023\nName: 4, dtype: object"
}

Analysis completed successfully.
Query executed successfully.

In [79]:
# Continuous interaction with dataset

while True:

    question = input(
        "\nEnter your question (type exit to stop): "
    )

    if question.lower() == "exit":

        print("Session ended successfully.")
        break

    analyze_data_with_groq(
        question,
        df
    )

Enter your question (type exit to stop): Display all student whose attendance is above 75
Starting AI data analysis.
Sending request to Groq.
Response received from Groq.

Generated Code:
--------------------------------
```python
import pandas as pd

# Assuming df is already created
df = pd.DataFrame({
    'student_id': [1001, 1002, 1003, 1004, 1005],
    'name': ['Aarav Sharma', 'Priya Patel', 'Rohit Verma', 'Sneha Reddy', 'Arjun Nair'],
    'age': [19, 20, 19, 20, 19],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male'],
    'department': ['Computer Science', 'Computer Science', 'Electronics', 'Mechanical', 'Computer Science'],
    'semester': [2, 2, 2, 2, 2],
    'math_score': [85, 76, 65, 70, 92],
    'science_score': [78, 82, 74, 80, 88],
    'english_score': [72, 88, 61, 75, 81],
    'programming_score': [91, 79, 55, 48, 95],
    'attendance_percentage': [92, 87, 78, 95, 90],
    'city': ['Mumbai', 'Ahmedabad', 'Delhi', 'Hyderabad', 'Kochi'],
    'admission_year': [2023, 2023, 2023, 2023, 2023]
})

# Filter students with attendance above 75
result = df[df['attendance_percentage'] > 75].to_json(orient='records')

print(result)
```
--------------------------------
Executing generated code.
[{"student_id":1001,"name":"Aarav Sharma","age":19,"gender":"Male","department":"Computer Science","semester":2,"math_score":85,"science_score":78,"english_score":72,"programming_score":91,"attendance_percentage":92,"city":"Mumbai","admission_year":2023},{"student_id":1002,"name":"Priya Patel","age":20,"gender":"Female","department":"Computer Science","semester":2,"math_score":76,"science_score":82,"english_score":88,"programming_score":79,"attendance_percentage":87,"city":"Ahmedabad","admission_year":2023},{"student_id":1003,"name":"Rohit Verma","age":19,"gender":"Male","department":"Electronics","semester":2,"math_score":65,"science_score":74,"english_score":61,"programming_score":55,"attendance_percentage":78,"city":"Delhi","admission_year":2023},{"student_id":1004,"name":"Sneha Reddy","age":20,"gender":"Female","department":"Mechanical","semester":2,"math_score":70,"science_score":80,"english_score":75,"programming_score":48,"attendance_percentage":95,"city":"Hyderabad","admission_year":2023},{"student_id":1005,"name":"Arjun Nair","age":19,"gender":"Male","department":"Computer Science","semester":2,"math_score":92,"science_score":88,"english_score":81,"programming_score":95,"attendance_percentage":90,"city":"Kochi","admission_year":2023}]
Code executed successfully.

JSON Output:
{
    "status": "success",
    "question": "Display all student whose attendance is above 75",
    "result": "[{\"student_id\":1001,\"name\":\"Aarav Sharma\",\"age\":19,\"gender\":\"Male\",\"department\":\"Computer Science\",\"semester\":2,\"math_score\":85,\"science_score\":78,\"english_score\":72,\"programming_score\":91,\"attendance_percentage\":92,\"city\":\"Mumbai\",\"admission_year\":2023},{\"student_id\":1002,\"name\":\"Priya Patel\",\"age\":20,\"gender\":\"Female\",\"department\":\"Computer Science\",\"semester\":2,\"math_score\":76,\"science_score\":82,\"english_score\":88,\"programming_score\":79,\"attendance_percentage\":87,\"city\":\"Ahmedabad\",\"admission_year\":2023},{\"student_id\":1003,\"name\":\"Rohit Verma\",\"age\":19,\"gender\":\"Male\",\"department\":\"Electronics\",\"semester\":2,\"math_score\":65,\"science_score\":74,\"english_score\":61,\"programming_score\":55,\"attendance_percentage\":78,\"city\":\"Delhi\",\"admission_year\":2023},{\"student_id\":1004,\"name\":\"Sneha Reddy\",\"age\":20,\"gender\":\"Female\",\"department\":\"Mechanical\",\"semester\":2,\"math_score\":70,\"science_score\":80,\"english_score\":75,\"programming_score\":48,\"attendance_percentage\":95,\"city\":\"Hyderabad\",\"admission_year\":2023},{\"student_id\":1005,\"name\":\"Arjun Nair\",\"age\":19,\"gender\":\"Male\",\"department\":\"Computer Science\",\"semester\":2,\"math_score\":92,\"science_score\":88,\"english_score\":81,\"programming_score\":95,\"attendance_percentage\":90,\"city\":\"Kochi\",\"admission_year\":2023}]"
}

Analysis completed successfully.

Enter your question (type exit to stop): exit
Session ended successfully.