In [36]:
import pandas as pd

print("libraries imported successfully!")

libraries imported successfully!

In [37]:
df=pd.read_csv("/content/student_performance.csv")
print ("dataset loaded successfully!")

dataset loaded successfully!

In [38]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [39]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [40]:
print("number of row and columns :",df.shape)

number of row and columns : (30, 13)

In [41]:
print("number of student(row)",df.shape[0])

number of student(row) 30

In [42]:
print("number of coloumns",df.shape[1])

number of coloumns 13

In [43]:
print("coloumn in the dataset")
print(df.columns.tolist())

coloumn in the dataset
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [44]:
df.columns.tolist()
#shows the column name within the dataset

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [45]:
print("Data Types")
print(df.dtypes)

Data Types
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [46]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [47]:
print("Missing Values in the column")
df.isnull().sum()

Missing Values in the column

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [48]:
df.isnull().sum().sum()

np.int64(0)

In [49]:
print("student name:")
print (df['name'])

student name:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [50]:
print("department in this dataset:")
print(df['department'].unique())

department in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [51]:
print("how many student per department ")
print(df['department'].value_counts())

how many student per department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [52]:
cs_student=df[df['department']=='Computer Science']
cs_student

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [53]:
print(f"number of computer science student:{len(cs_student)}")

number of computer science student:13

In [54]:
print("computer science student:")
print(cs_student[['name','math_score','programming_score','attendance_percentage']])

computer science student:
              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
1      Priya Patel          76                 79                     87
4       Arjun Nair          92                 95                     90
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
12      Suresh Rao          83                 88                     88
14     Ajay Tiwari          71                 76                     75
17  Swati Kulkarni          90                 92                     94
19    Nisha Kapoor          79                 83                     89
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
26   Gaurav Shukla          84                 87                     87
29  Akanksha Yadav          91                 94                     95

In [55]:
high_attendance=df[df['attendance_percentage']>90]
high_attendance

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [56]:
print(f"students with attendance above 90%:{len(high_attendance)}")

students with attendance above 90%:10

In [57]:
print(high_attendance[['name','math_score','programming_score','attendance_percentage']])

              name  math_score  programming_score  attendance_percentage
0     Aarav Sharma          85                 91                     92
3      Sneha Reddy          70                 48                     95
7      Divya Singh          88                 93                     96
9       Ananya Das          95                 97                     98
13   Kavya Nambiar          74                 51                     91
15    Ritu Agarwal          87                 69                     93
17  Swati Kulkarni          90                 92                     94
21     Tanvi Mehta          93                 96                     97
24       Amit Bose          86                 89                     91
29  Akanksha Yadav          91                 94                     95

In [58]:
print(high_attendance[['student_id','name','department','attendance_percentage']])

    student_id            name        department  attendance_percentage
0         1001    Aarav Sharma  Computer Science                     92
3         1004     Sneha Reddy        Mechanical                     95
7         1008     Divya Singh  Computer Science                     96
9         1010      Ananya Das  Computer Science                     98
13        1014   Kavya Nambiar        Mechanical                     91
15        1016    Ritu Agarwal       Electronics                     93
17        1018  Swati Kulkarni  Computer Science                     94
21        1022     Tanvi Mehta  Computer Science                     97
24        1025       Amit Bose  Computer Science                     91
29        1030  Akanksha Yadav  Computer Science                     95

In [59]:
total_score=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
print(total_score)

0     326
1     325
2     255
3     273
4     356
5     246
6     247
7     356
8     236
9     371
10    295
11    262
12    334
13    285
14    280
15    325
16    210
17    354
18    252
19    327
20    259
21    367
22    228
23    287
24    336
25    285
26    325
27    232
28    271
29    365
dtype: int64

In [60]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
top_student=df.loc[df['total_score'].idxmax()]
print(top_student)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                           371
Name: 9, dtype: object

In [61]:
top_student=df.loc[df['total_score'].idxmax()]
print(top_student)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                           371
Name: 9, dtype: object

In [62]:
print("top student")
print("name",top_student['name'])
print("department",top_student['department'])
print("total score",top_student['total_score'])
print("attendence percentage",top_student['attendance_percentage'])

top student
name Ananya Das
department Computer Science
total score 371
attendence percentage 98

In [63]:
df_sorted=df.sort_values(by='total_score', ascending=False)
print(df_sorted.head())

    student_id            name  age  gender        department  semester  \
9         1010      Ananya Das   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
9           95             89             90                 97
21          93             90             88                 96
29          91             93             87                 94
4           92             88             81                 95
7           88             91             84                 93

    attendance_percentage     city  admission_year  total_score
9                      98  Kolkata            2023          371
21                     97    Surat            2023          367
29                     95     Agra            2023          365
4                      90    Kochi            2023          356
7                      96  Lucknow            2023          356

In [64]:
dept_avg = df.groupby('department')['total_score'].mean().round(2)
dept_avg

department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

# **Practice Questions**

In [65]:
#How many students are from the electronics department
electronics_students = df[df['department'] == 'Electronics']
print("Number of students from Electronics department:", len(electronics_students))

Number of students from Electronics department: 6

In [66]:
#What is the average attendance of the electronics department
electronics_students = df[df['department'] == 'Electronics']
avg_attendance = electronics_students['attendance_percentage'].mean()
print("Average attendance of Electronics department:", avg_attendance)

Average attendance of Electronics department: 80.33333333333333

In [67]:
#Who is the student with the lowest programming score
lowest_programming_score = df['programming_score'].min()
student_with_lowest_programming = df[df['programming_score'] == lowest_programming_score]
print("Student with the lowest programming score:")
print(student_with_lowest_programming[['name', 'programming_score']])

Student with the lowest programming score:
            name  programming_score
16  Manoj Pandey                 38

In [68]:
#How many stdent scored above 80 in Math
math_above_80 = df[df['math_score'] > 80]
print("Number of students scoring above 80 in Math:", len(math_above_80))

Number of students scoring above 80 in Math: 11

**What is the average total_score for students with attendance above 90%**

In [69]:
#What is the average total_score for students with attendance above 90%
above_90_attendance = df[df['attendance_percentage'] > 90]
avg_total_score = above_90_attendance['total_score'].mean()
avg_total_score

np.float64(335.8)

#**MINI project:Student Data Explorer**


Objective:

Create a student Performance explorer using python and pandas to analyze the student data and generate a detailed report

#*Dataset columns:*

name

gender

department

math_score

programming_score

attendance_percentage

total_score

Tasks to perform:

**1.Display project file.**
print a formatted title with seperate lines.

2.DataSet Overview

Display:

-Total number of students

-Total number of columns

-Number of unique departments

3.Department wise Analysis

Display the count of students in each department.

4.Score Analysis

Find and display:

-Highest math score

-Lowest math score

-Average math score

-Average programming score

-Average attendance percentage

5.Gender wise analysis

Calculate and Display average total score grouped by gender

6.Top Performers:

Calculate the top 5 students based on total_score

show:

-Student Name

-Department

-Total Score

7.Attendance Analysis

Find student whose attendance is below 75%

Display:

-Name

-Department

-Attendance Percentage

If all the students have attendance above 75%

print a suitable message

concepts to use:

-pandas, DataFrame, groupby(), value_count(), mean(), max(), min(), sort_values(), conditional statements, f-strings

**1.Display project file. print a formatted title with seperate lines.**

#=======================================
#    STUDENT DATA EXPLORER PROGRAM
#=======================================

**2.Dataset Overview**

In [70]:
#Total number of students
len(df)

30

In [71]:
#Total number of columns
df.shape[1]

14

In [72]:
#Number of unique departments
department=df['department'].unique()
len(department)

4

**3.Department wise Analysis**

In [73]:
#Display the count of students in each department
df['department'].value_counts()

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

**4.Score Analysis**

In [74]:
#Highest math score
print('Highest Math score : ',df['math_score'].max())

Highest Math score :  95

In [75]:
#Lowest Math Score
print('Lowest Math Score : ',df['math_score'].min())

Lowest Math Score :  56

In [76]:
#Average Math Score
print('Average Math Score : ',df['math_score'].mean())

Average Math Score :  76.06666666666666

In [77]:
#Average Programming score
print('Average Programming score : ',df['programming_score'].mean())

Average Programming score :  67.6

In [78]:
#Average Attendance Percentage
print('Average Attendance Percentage : ',df['attendance_percentage'].mean())

Average Attendance Percentage :  84.5

**5.Gender wise Analysis**

In [79]:
#Average total score grouped by gender
df.groupby('gender')['total_score'].mean()

gender
Female    310.666667
Male      280.666667
Name: total_score, dtype: float64

**6.Top performers**

In [80]:
#top 5 students based on total_score
top_students = df.nlargest(5, 'total_score')
print(top_students[['name', 'department', 'total_score']])

              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

**7.Attendance Analysis**

In [81]:
#students below 75% attendance
df[df['attendance_percentage'] < 75]

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023,246
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023,236
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023,210
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023,259
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023,228
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023,232

In [82]:
import pandas as pd

print("-" * 60)
print(f"{'STUDENT DATA EXPLORER':^60}")
print(f"{'Mini Project Report':^60}")
print("-" * 60)

# =================== 1. PROJECT TITLE DONE ABOVE ===================


# =================== 2. DATASET OVERVIEW ===================
print("\n" + "=" * 50)
print("        DATASET OVERVIEW")
print("=" * 50)

print(f"Total number of students   : {len(df)}")
print(f"Total number of columns    : {len(df.columns)}")
print(f"Number of unique departments: {df['department'].nunique()}")


# =================== 3. DEPARTMENT WISE ANALYSIS ===================
print("\n" + "=" * 50)
print("   DEPARTMENT WISE ANALYSIS")
print("=" * 50)

dept_counts = df["department"].value_counts()
for department, count in dept_counts.items():
    print(f"{department:<20} : {count} students")


# =================== 4. SCORE ANALYSIS ===================
print("\n" + "=" * 50)
print("         SCORE ANALYSIS")
print("=" * 50)

print(f"Highest math score              : {df['math_score'].max():>3}")
print(f"Lowest math score               : {df['math_score'].min():>3}")
print(f"Average math score              : {df['math_score'].mean():5.2f}")
print(f"Average programming score       : {df['programming_score'].mean():5.2f}")
print(f"Average attendance percentage   : {df['attendance_percentage'].mean():5.2f} %")


# =================== 5. GENDER WISE ANALYSIS ===================
print("\n" + "=" * 50)
print("   GENDER WISE ANALYSIS (Average Total Score)")
print("=" * 50)

# Create total_score = math + programming
df["total_score"] = df["math_score"] + df["programming_score"]
gender_avg = df.groupby("gender")["total_score"].mean()

for gender, avg_score in gender_avg.items():
    print(f"{gender:<8} : {avg_score:6.2f}")


# =================== 6. TOP PERFORMERS ===================
print("\n" + "=" * 50)
print("             TOP 5 PERFORMERS")
print("=" * 50)

top_5 = df.sort_values("total_score", ascending=False).head(5)[["name", "department", "total_score"]]
print(f"{'Name':<20} {'Department':<15} {'Total Score'}")
print("-" * 50)
for _, row in top_5.iterrows():
    print(f"{row['name']:<20} {row['department']:<15} {row['total_score']}")


# =================== 7. ATTENDANCE ANALYSIS ===================
print("\n" + "=" * 50)
print("         ATTENDANCE ANALYSIS (Below 75%)")
print("=" * 50)

low_att = df[df["attendance_percentage"] < 75]
if low_att.empty:
    print("All students have attendance above or equal to 75%.")
else:
    print(f"{'Name':<20} {'Department':<15} {'Attendance %'}")
    print("-" * 50)
    for _, row in low_att.iterrows():
        print(f"{row['name']:<20} {row['department']:<15} {row['attendance_percentage']:>10}%")

------------------------------------------------------------
                   STUDENT DATA EXPLORER
                    Mini Project Report
------------------------------------------------------------

==================================================
        DATASET OVERVIEW
==================================================
Total number of students   : 30
Total number of columns    : 14
Number of unique departments: 4

==================================================
   DEPARTMENT WISE ANALYSIS
==================================================
Computer Science     : 13 students
Electronics          : 6 students
Mechanical           : 6 students
Civil                : 5 students

==================================================
         SCORE ANALYSIS
==================================================
Highest math score              :  95
Lowest math score               :  56
Average math score              : 76.07
Average programming score       : 67.60
Average attendance percentage   : 84.50 %

==================================================
   GENDER WISE ANALYSIS (Average Total Score)
==================================================
Female   : 148.67
Male     : 138.67

==================================================
             TOP 5 PERFORMERS
==================================================
Name                 Department      Total Score
--------------------------------------------------
Ananya Das           Computer Science 192
Tanvi Mehta          Computer Science 189
Arjun Nair           Computer Science 187
Akanksha Yadav       Computer Science 185
Swati Kulkarni       Computer Science 182

==================================================
         ATTENDANCE ANALYSIS (Below 75%)
==================================================
Name                 Department      Attendance %
--------------------------------------------------
Meera Joshi          Electronics             72%
Rahul Mishra         Mechanical              68%
Manoj Pandey         Civil                   65%
Harish Pillai        Electronics             74%
Sanjay Dubey         Civil                   70%
Sunita Pillai        Civil                   73%