In [ ]:
import pandas as pd

In [ ]:
a=pd.read_csv("/content/SOCR-HeightWeight.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [ ]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
a.isnull().any()              # shows as True or False

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
a.isnull().sum()       # shows as the numbers

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
x=a[["Height(Inches)"]]
x

       Height(Inches)
0            65.78331
1            71.51521
2            69.39874
3            68.21660
4            67.78781
...               ...
24995        69.50215
24996        64.54826
24997        64.69855
24998        67.52918
24999        68.87761

[25000 rows x 1 columns]

In [ ]:
y=a[["Weight(Pounds)"]]
y

       Weight(Pounds)
0            112.9925
1            136.4873
2            153.0269
3            142.3354
4            144.2971
...               ...
24995        118.0312
24996        120.1932
24997        118.2655
24998        132.2682
24999        124.8742

[25000 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print("X train")
x_train

X train

       Height(Inches)
19764        70.57061
22678        67.90465
9295         70.94818
4644         66.26386
148          68.71053
...               ...
14141        65.33009
15563        65.47246
1402         66.13808
12896        65.23885
2120         71.05207

[20000 rows x 1 columns]

In [ ]:
print("Y train")
y_train

Y train

       Weight(Pounds)
19764        147.3327
22678        120.3374
9295         149.7548
4644         110.0377
148          130.7568
...               ...
14141        112.1983
15563        125.9926
1402         136.9275
12896        137.3238
2120         149.7790

[20000 rows x 1 columns]

In [ ]:
print("X test")
x_test

X test

       Height(Inches)
6192         65.44403
2799         68.37223
23348        65.29888
5763         67.68617
22698        64.09194
...               ...
5236         66.74599
21846        68.63389
2620         67.00444
8385         69.18567
3872         67.84537

[5000 rows x 1 columns]

In [ ]:
print("Y test")
y_test

Y test

       Weight(Pounds)
6192        109.92320
2799        140.64620
23348       126.19830
5763        132.64570
22698       119.32240
...               ...
5236        114.69310
21846       114.56550
2620         93.78282
8385        128.02750
3872        132.63790

[5000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

8.000862145808336

In [ ]:
mean_squared_error(y_test,y_pred)

100.84849228263717

In [ ]:
r2_score(y_test,y_pred)

0.24698354688844848

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"linear")

['linear']

In [ ]:
import joblib

In [ ]:
a=joblib.load('linear.pkl')

In [ ]:
a.predict([[100]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[225.84734392]])