In [3]:
import pandas as pd

In [4]:
a=pd.read_csv("/content/SOCR-HeightWeight.csv")
print("Dataset Loaded Successfully")

Dataset Loaded Successfully

In [5]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [6]:
a.isnull().any()              # shows as True or False

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [7]:
a.isnull().sum()       # shows as the numbers

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [8]:
x=a[["Height(Inches)"]]
x

       Height(Inches)
0            65.78331
1            71.51521
2            69.39874
3            68.21660
4            67.78781
...               ...
24995        69.50215
24996        64.54826
24997        64.69855
24998        67.52918
24999        68.87761

[25000 rows x 1 columns]

In [9]:
y=a[["Weight(Pounds)"]]
y

       Weight(Pounds)
0            112.9925
1            136.4873
2            153.0269
3            142.3354
4            144.2971
...               ...
24995        118.0312
24996        120.1932
24997        118.2655
24998        132.2682
24999        124.8742

[25000 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
print("X train")
x_train

X train

       Height(Inches)
23363        69.52961
23693        65.34486
19765        69.44979
18505        65.57553
24650        69.79279
...               ...
2194         66.50974
16705        69.08954
16776        67.41631
1239         66.33003
13815        66.63132

[20000 rows x 1 columns]

In [13]:
print("Y train")
y_train

Y train

       Weight(Pounds)
23363        139.0711
23693        111.9794
19765        123.2579
18505        132.8521
24650        131.8303
...               ...
2194         123.1286
16705        128.0095
16776        117.7373
1239         123.2428
13815        130.1165

[20000 rows x 1 columns]

In [14]:
print("X test")
x_test

X test

       Height(Inches)
19212        65.14711
18140        67.17728
6919         67.53601
13463        66.35698
22171        67.10339
...               ...
22009        69.44904
18570        69.46167
10432        69.58810
24582        67.35479
12171        68.94674

[5000 rows x 1 columns]

In [15]:
print("Y test")
y_test

Y test

       Weight(Pounds)
19212        117.8660
18140        130.4030
6919         127.3499
13463        117.5543
22171        127.6042
...               ...
22009        126.7259
18570        129.6969
10432        128.1330
24582        120.6077
12171        140.2945

[5000 rows x 1 columns]

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
model=LinearRegression()

In [18]:
model.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred=model.predict(x_test)

In [20]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [21]:
mean_absolute_error(y_test,y_pred)

8.120618991616846

In [22]:
mean_squared_error(y_test,y_pred)

103.66213523432715

In [23]:
r2_score(y_test,y_pred)

0.24464177977924018

In [24]:
import joblib

In [25]:
joblib.dump(model,"linear")

['linear']

In [26]:
import joblib

In [28]:
a=joblib.load('linear')

In [29]:
a.predict([[100]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[225.99408373]])